import assert from "node:assert/strict";
import { createServer, type IncomingMessage } from "node:http";
import type { AddressInfo } from "node:net";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { callPythonRuntimeService } from "../server/modelRuntime/pythonRuntimeService";
import { analyzeTimelineWithVlm, refineRelatedKnowledgeTimelineWithVlm } from "../server/vlmWorkerClient";
import type { AssetRecord, IndexRecord, TimelineSegment } from "../shared/types";

test("Python runtime service calls ignore deprecated timeout environment settings", async () => {
  const server = await startJsonServer(async (_req) => {
    await delay(30);
    return {
      ok: true,
      result: {
        available: true,
        provider: "test-runtime"
      }
    };
  });
  const previous = snapshotEnv(["PYTHON_RUNTIME_SERVICE_URL", "PYTHON_RUNTIME_SERVICE_TIMEOUT_MS", "PYTHON_RUNTIME_SERVICE_ATTEMPTS"]);
  try {
    process.env.PYTHON_RUNTIME_SERVICE_URL = server.url;
    process.env.PYTHON_RUNTIME_SERVICE_TIMEOUT_MS = "1";
    process.env.PYTHON_RUNTIME_SERVICE_ATTEMPTS = "1";

    const result = await callPythonRuntimeService<{ available: boolean; provider: string }>("runtime", "/slow-runtime", {}, { metricKey: "test.runtime_boundary.python" });

    assert.deepEqual(result, { available: true, provider: "test-runtime" });
  } finally {
    restoreEnv(previous);
    await server.close();
  }
});

test("VLM worker analysis and refinement ignore deprecated timeout environment settings", async () => {
  const paths: string[] = [];
  const server = await startJsonServer(async (req) => {
    paths.push(req.url ?? "");
    await delay(30);
    if (req.url === "/analyze/video-segment") {
      return {
        provider: "test-vlm",
        model: "test-vlm-model",
        caption: "Player receives the ball near midfield.",
        description: "A visible player controls possession.",
        sceneType: "sports",
        confidence: 0.88,
        labels: ["sports.football"],
        objects: ["player", "ball"],
        actions: ["receive"],
        visibleText: [],
        evidence: ["Generated by regression test."]
      };
    }
    if (req.url === "/structure/sports-event") {
      return {
        domain: "sports.football",
        provider: "test-vlm",
        model: "test-vlm-model",
        caption: "Midfield pass reception.",
        eventType: "pass_receive",
        confidence: 0.91,
        labels: ["sports.football", "pass_receive"],
        evidence: ["Generated by regression test."],
        football: {
          phase: "attack",
          fieldZone: "middle_third",
          passType: "short_pass",
          receivingPlayer: { present: false, name: null, confidence: 0 },
          passingPlayer: { present: false, name: null, confidence: 0 },
          ballState: "in_play",
          attackingDirection: "unknown"
        }
      };
    }
    return { ok: false, error: `Unexpected path: ${req.url}` };
  });
  const previous = snapshotEnv(["VLM_WORKER_URL", "VLM_WORKER_MODEL", "VLM_WORKER_TIMEOUT_MS"]);
  try {
    process.env.VLM_WORKER_URL = server.url;
    process.env.VLM_WORKER_MODEL = "test-vlm-model";
    process.env.VLM_WORKER_TIMEOUT_MS = "1";

    const analysis = await analyzeTimelineWithVlm(baseAsset(), [baseSegment()]);
    assert.equal(analysis.describedSegments, 1);
    assert.equal(analysis.failedSegments, 0);
    assert.equal(analysis.timeline[0]?.sceneData?.vlm?.status, "described");

    const refinement = await refineRelatedKnowledgeTimelineWithVlm(baseAsset(), baseIndex(), [baseSegment()]);
    assert.equal(refinement.refinedSegments, 1);
    assert.equal(refinement.failedSegments, 0);
    assert.equal(refinement.timeline[0]?.domain?.vlm?.status, "refined");

    assert.deepEqual(paths, ["/analyze/video-segment", "/structure/sports-event"]);
  } finally {
    restoreEnv(previous);
    await server.close();
  }
});

test("long-running runtime boundaries do not reintroduce timeout cutoffs", async () => {
  const files = await collectRuntimeBoundaryFiles(process.cwd());
  const forbidden = [
    "AbortSignal.timeout",
    "PYTHON_RUNTIME_SERVICE_TIMEOUT",
    "WHISPER_TIMEOUT",
    "WHISPERX_TIMEOUT",
    "PADDLEOCR_TIMEOUT",
    "VLM_WORKER_TIMEOUT",
    "EMBEDDING_TIMEOUT",
    "VISUAL_EMBEDDING_TIMEOUT",
    "SCENE_TIMEOUT",
    "VISION_DETECTOR_TIMEOUT",
    "VISION_TRACKER_TIMEOUT",
    "SOCCERNET_ACTION_SPOTTING_TIMEOUT",
    "MODEL_DOCTOR_TIMEOUT",
    "safety limit"
  ];

  const violations: string[] = [];
  for (const file of files) {
    const text = await readFile(file, "utf8");
    for (const token of forbidden) {
      if (text.includes(token)) violations.push(`${path.relative(process.cwd(), file)} contains ${token}`);
    }
  }

  assert.deepEqual(violations, []);
});

test("Python model HTTP services keep blocking model work off the event loop", async () => {
  const runtimeService = await readFile(path.resolve("scripts", "arion_model_runtime_service.py"), "utf8");
  assert.match(runtimeService, /asyncio\.create_subprocess_exec/);
  assert.match(runtimeService, /TEXT_EMBEDDING_MODELS/);
  assert.match(runtimeService, /VISUAL_EMBEDDING_MODELS/);
  assert.match(runtimeService, /asyncio\.to_thread\(encode_text_embeddings/);
  assert.match(runtimeService, /asyncio\.to_thread\(encode_visual_embeddings/);
  assert.doesNotMatch(runtimeService, /subprocess\.run/);
  assert.doesNotMatch(runtimeService, /timeout_ms/);

  const vlmWorker = await readFile(path.resolve("scripts", "qwen_vlm_worker.py"), "utf8");
  assert.match(vlmWorker, /asyncio\.to_thread\(_generate_text_locked/);
  assert.match(vlmWorker, /asyncio\.to_thread\(_generate_video_text_locked/);
  assert.match(vlmWorker, /MODEL_GENERATION_LOCK/);
});

test("ASR partials are merged before slower diarization and OCR stages finish", async () => {
  const speechRuntime = await readFile(path.resolve("server", "modelRuntime", "speechRuntime.ts"), "utf8");
  const asrPublishIndex = speechRuntime.indexOf("await options.onWhisper?.(whisper);");
  const diarizationIndex = speechRuntime.indexOf("await runWhisperXStage");
  assert.ok(asrPublishIndex > -1, "runSpeechRuntime should expose a post-ASR callback");
  assert.ok(diarizationIndex > -1, "runSpeechRuntime should still run diarization after ASR");
  assert.ok(asrPublishIndex < diarizationIndex, "ASR callback must run before diarization starts");

  const localModelRuntime = await readFile(path.resolve("server", "localModelRuntime.ts"), "utf8");
  assert.match(localModelRuntime, /onWhisper: async \(whisper\) => \{\s*await publishRuntimePartial\(options, "asr", \{ asr: buildAsrIntelligence\(whisper\) \}\);/s);
  assert.match(localModelRuntime, /segments: applyDiarizationToAsrSegments\(whisper\.segments, diarizationSegments\)/);
});

async function startJsonServer(handler: (req: IncomingMessage) => Promise<unknown>) {
  const server = createServer(async (req, res) => {
    try {
      const payload = await handler(req);
      res.writeHead(200, { "content-type": "application/json" });
      res.end(JSON.stringify(payload));
    } catch (error) {
      res.writeHead(500, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: error instanceof Error ? error.message : "test server failed" }));
    }
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  assert.ok(isAddressInfo(address));
  return {
    url: `http://127.0.0.1:${address.port}`,
    close: () => new Promise<void>((resolve, reject) => server.close((error) => (error ? reject(error) : resolve())))
  };
}

function isAddressInfo(address: string | AddressInfo | null): address is AddressInfo {
  return Boolean(address) && typeof address === "object";
}

async function collectRuntimeBoundaryFiles(root: string) {
  const includedRoots = [
    path.resolve(root, "server", "modelRuntime"),
    path.resolve(root, "server", "vision"),
    path.resolve(root, "server", "knowledge", "adapters", "sports", "football", "soccernet"),
    path.resolve(root, "server", "knowledge", "adapters", "sports", "americanFootball", "actionSpotting")
  ];
  const includedFiles = new Set(
    [
      "server/analysisGenerator.ts",
      "server/localEmbeddingRuntime.ts",
      "server/localVisualEmbeddingRuntime.ts",
      "server/modelCapabilities.ts",
      "server/sceneDetection.ts",
      "server/vlmWorkerClient.ts",
      "scripts/arion_model_runtime_service.py",
      "scripts/qwen_vlm_worker.py",
      ".env.example",
      ".env.docker",
      "docs/architecture.md"
    ].map((item) => path.resolve(root, item))
  );
  const discovered = await collectFiles(path.resolve(root, "server"));
  return [
    ...discovered.filter((file) => includedRoots.some((prefix) => file.startsWith(`${prefix}${path.sep}`)) || includedFiles.has(file)),
    ...Array.from(includedFiles).filter((file) => !discovered.includes(file))
  ];
}

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) return collectFiles(fullPath);
      if (entry.isFile()) return [fullPath];
      return [];
    })
  );
  return nested.flat();
}

function baseAsset(): AssetRecord {
  return {
    id: "asset-1",
    indexId: "index-1",
    title: "Sample asset",
    description: "",
    originalName: "sample.mp4",
    storedName: "local-s3/bucket/assets/sample.mp4",
    mimeType: "video/mp4",
    size: 1024,
    duration: 60,
    width: 1920,
    height: 1080,
    status: "indexed",
    progress: 100,
    tags: [],
    summary: "",
    timeline: [],
    keyframes: [],
    technicalMetadata: {
      storageProvider: "local-s3",
      bucket: "bucket",
      objectKey: "assets/sample.mp4",
      checksum: null,
      frameRate: 30,
      audioCodec: "aac",
      videoCodec: "h264"
    },
    intelligence: {
      audio: { extractedPath: null, speechSegments: [], musicSegments: [], hasSpeech: false, hasMusic: false },
      asr: { transcript: "", language: "unknown", confidence: 0, segments: [] },
      diarization: { provider: "none", speakers: [], segments: [], error: null },
      ocr: { tokens: [], confidence: 0, frames: [] },
      visual: { labels: [], dominantColor: "#000000", brightness: 0, motionScore: 0 },
      modelTrace: []
    },
    error: null,
    createdAt: "2026-05-04T18:00:00.000Z",
    updatedAt: "2026-05-04T18:00:00.000Z"
  };
}

function baseIndex(): IndexRecord {
  return {
    id: "index-1",
    name: "Sample index",
    description: "",
    models: { search: "local", analysis: "local", embedding: "local" },
    modalities: ["visual", "audio", "transcription", "metadata"],
    domainIndexing: {
      enabled: true,
      groups: ["sports.football"],
      stages: ["domain_caption", "event_label", "structured_event"]
    },
    capabilityPolicy: {
      whisperXDiarization: "optional",
      videoVlmAnalysis: "optional",
      visionDetector: "optional",
      visionTracker: "optional",
      knowledgeActionSpotting: "optional",
      domainVlmRefinement: "optional"
    },
    assetIds: ["asset-1"],
    status: "ready",
    createdAt: "2026-05-04T18:00:00.000Z",
    updatedAt: "2026-05-04T18:00:00.000Z"
  };
}

function baseSegment(): TimelineSegment {
  return {
    id: "segment-1",
    start: 0,
    end: 5,
    label: "Sample segment",
    transcript: "",
    sceneData: {
      image: {
        thumbnailPath: null,
        framePath: "/tmp/arion-test-frame.jpg",
        labels: [],
        dominantColor: "#000000",
        brightness: 0,
        motionScore: 0,
        keyframeAt: 2.5
      },
      text: {
        speech: "",
        subtitles: [],
        screenText: [],
        overlays: [],
        watermarks: [],
        comparisons: []
      }
    },
    tags: [],
    modalities: ["visual"],
    confidence: 0.8,
    embedding: [],
    thumbnailPath: null,
    sources: ["visual"]
  };
}

function snapshotEnv(keys: string[]) {
  return new Map(keys.map((key) => [key, process.env[key]]));
}

function restoreEnv(snapshot: Map<string, string | undefined>) {
  for (const [key, value] of snapshot) {
    if (typeof value === "undefined") delete process.env[key];
    else process.env[key] = value;
  }
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
